import Footer from "@/components/footer/footer";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} min-h-screen flex flex-col w-full antialiased`}>
        <div className="flex flex-col items-center justify-center flex-1 bg-white dark:bg-neutral- text-black">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
